cmake: Fix fuzzer "multiple definition of `main'" errors
This change is technically not needed to add libmultiprocess as a subtree, but
it avoids a CI failure in followup PR #30975 which enables multiprocess build
option in more CI jobs. Specifically this makes it possible to use the
BUILD_FOR_FUZZING and ENABLE_IPC options together easily.

The change just updates the cmake build so when -DSANITIZERS=fuzzer is
specified, the fuzz test binary is built with -fsanitize=fuzzer (so it can use
libFuzzer's main function), and libraries are built with
-fsanitize=fuzzer-no-link (so they can be linked into other executables with
their own main functions).

Previously when -DSANITIZERS=fuzzer was specified, -fsanitize=fuzzer was added
to core_interface build flags and applied to ALL libraries and executables.
This was inappropriate because it made it impossible to build any executables
other than the fuzz test executable without triggering link errors:

- "multiple definition of `main'"
- "undefined reference to `LLVMFuzzerTestOneInput'"

if they depended on any libraries instrumented for fuzzing.

This was especially a problem when the ENABLE_IPC option was set because it
caused all libmultiprocess executables to fail to link with errors above
because they depend indirectly on core_interface.

More specifically, this prevented the mpgen code generator from being built, so
generated sources could not be fuzz tested, and it was impossible to enable
BUILD_FOR_FUZZING and ENABLE_IPC options together without providing an external
mpgen binary, which would require a separate build and be cumbersome to set up.